
spring:
  h2:
    console:
      enabled: true
  zipkin:
    base-url: http://localhost:9411/zipkin/    
  application:
    name: ORDER-SERVICE   
  cloud:
    compatibility-verifier:
      enabled: false
logging:
  file: 
    name:  C:\Users\mkurimeti\ELK STACK\microservice-logs.log   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/      
  instance:
    hostname: localhost
    
    